Created check in methods for load and capacity
raniazqt/HW_Airport pull request #29
Opened 2020-03-14 13:25 UTC by ugavi

2020-03-15 12:25 UTC, raniazqt requested changes
Please review the comments and fix code where needed

2020-03-15 12:25 UTC, raniazqt commented on src/com/hw/airport/service/CheckInSvcImpl.java
> +
you shouldn't chain the call to get the flight code. NullPointerException will be thrown if bookingRef is not found. You also need to handle this case by throwing the proper exception

2020-03-15 12:25 UTC, raniazqt commented on src/com/hw/airport/service/FlightSvcImpl.java
> +		int currentCheckedInPsngrCount = 0;
Existing code should be utilized to save time and effort. There is a method already implemented which returns the list of bookings for a given flight [public List<Booking> findAllBookingForFlight(String flightCode) ]
Then loop over the list and check the booking status.

2020-03-15 12:25 UTC, raniazqt commented on src/com/hw/airport/service/FlightSvcImpl.java
> +		for(Booking booking : appData.getBookingList().values()) {
when comparing strings, always use equalsIgnoreCase

2020-03-15 12:25 UTC, raniazqt commented on src/com/hw/airport/service/FlightSvcImpl.java
> +			if(isBookingOnFlightAndCheckedIn) {
To simplify the code, no need to define a variable to hold the Boolean value. you can just use it directly in the "if statement " condition clause

2020-03-15 12:25 UTC, raniazqt commented on src/com/hw/airport/service/FlightSvcImpl.java
> +
remove the baggageService since it is not used here

2020-03-15 12:25 UTC, raniazqt commented on src/com/hw/airport/service/CheckInSvcImpl.java
> +
remove the lastName attribute since it is not needed.

2020-04-21 03:22 UTC, mhserry approved these changes

2020-08-02 16:30 UTC, raniazqt commented
outdated

2020-08-02 16:30 UTC, closed without merging